[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.20'
remappings = [
    "ds-test/=contracts/lib/forge-std/lib/ds-test/src/",
    "forge-std/=contracts/lib/forge-std/src/",
    "openzeppelin/=contracts/lib/openzeppelin/contracts/",
    "openzeppelinUpgradeable/=contracts/lib/openzeppelinUpgradeable/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config